#!/bin/bash
# Author: FlyinGrub
# Check my github : https://github.com/flyingrub/soundcloud-dl
# Share it if you like ;)
##############################################################
echo ''
echo ' *---------------------------------------------------------------------------*'
echo '|                             SCDL Installer                                  |'
echo ' *---------------------------------------------------------------------------*'
echo ''

function menu() {
    clear
    PS3='Please enter your choice: '
    options=("Install" "Set the path where to download Music" "Set the behaviour when the script encounter a music that already exist" "Quit")
    select opt in "${options[@]}"
    do
        if [ "$opt" = "Install" ]; then
            install
        elif [ "$opt" = "Set the path where to download Music" ]; then
            setpath
        elif [ "$opt" = "Set the behaviour when the script encounter a music that already exist" ]; then
            setcon
        elif [ "$opt" = "Quit" ]; then
            quit
        else
            clear
            echo 'Bad option'
        fi
    done
}

function install() {
    detectedOS
    if [[ "$platform" == 'linux' ]]; then
        sudo apt-get update
        sudo apt-get install curl
        sudo apt-get install eyeD3
        sudo cp scdl /usr/bin/scdl
    elif [[ "$platform" == 'redhat' ]]; then
        sudo yum install curl python-eyed3 recode
        sudo cp scdl /usr/bin/scdl
    elif [[ "$platform" == 'arch' ]]; then
        sudo pacman -S curl python2-eyed3
        sudo cp scdl /usr/bin/scdl
    elif [[ "$platform" == 'darwin' ]]; then
        sudo cp scdl /opt/local/bin/scdl
    fi
    menu
}

function setpath() {
    echo "Where do you want to download your Music?"
    read -p 'path : ' path
    if [ -d $path ]; then
        echo -e 'pathtomusic="'"$path"'"'"\n"'continue="'"$cont"'"' > /$HOME/.scdl.cfg
        echo 'Path set !'
        echo ''
    else
        echo 'The path do not exist...'
        read -p 'Would you like to Create it? (y/n)?' choice
        if [ "$choice" = "y" ]; then
            mkdir $path
            echo -e 'pathtomusic="'"$path"'"'"\n"'continue="'"$cont"'"' > /$HOME/.scdl.cfg
            echo 'Path set !'
            echo ''
        else
            setpath
        fi
    fi
}

function setcon() {
    read -p "Would you like to stop the script when it encounter a music that already exist ?(y/n)" choice
    if [ "$choice" = "y" ]; then
        cont="false"
        echo -e 'pathtomusic="'"$path"'"'"\n"'continue="'"$cont"'"' > /$HOME/.scdl.cfg
        echo 'The script will exit if it encounter a file that already exist'
        echo ''
    elif [ "$choice" = "n" ]; then
        cont="true"
        echo -e 'pathtomusic="'"$path"'"'"\n"'continue="'"$cont"'"' > /$HOME/.scdl.cfg
        echo 'The script will skip the music that already exist'
        echo ''
    else
        echo 'Bad option'
        setcon
    fi
}

function quit() {
    read -p 'Do you really want to leave the installer ?(y/n)' quit
    if [ "$quit" = "y" ]; then
        echo 'Bye !'
        exit
    elif [ "$quit" = "n" ]; then
        echo ''
        menu
    else
        echo 'Bad option'
        quit
    fi
}

function detectedOS(){
    unamestr=`uname`
        if [[ "$unamestr" == 'Linux' ]]; then
            if [[ -f /etc/redhat-release ]]; then
                platform='redhat'
            else
                platform='linux'
            fi
        if [[ -f /etc/arch-release ]]; then
            platform='arch'
        fi

    elif [[ "$unamestr" == 'Darwin' ]]; then
       platform='darwin'
    fi
}

if [ -f /$HOME/.scdl.cfg ]; then
    source /$HOME/.scdl.cfg
    path=$pathtomusic
    cont=$continue
    menu
else
    echo 'No Config file detected... I will install scdl for you.'
    echo ''
    install
    setpath
    setcon
    exit
fi

