#!/bin/bash
# Author: FlyinGrub
# Check my github : https://github.com/flyingrub/soundcloud-dl
# Share it if you like ;)
##############################################################

echo ''
echo ' *---------------------------------------------------------------------------*'
echo '|               SoundcloudMusicDownloader           |   FlyinGrub rework      |'
echo ' *---------------------------------------------------------------------------*'

function CURL(){
    curl -s --user-agent 'Mozilla/5.0' "$1"
}

function config() {
    if [ -f /$HOME/.scdl.cfg ]; then
        source /$HOME/.scdl.cfg
        if [ "$continue" = "true" ]; then
            cont=continue
        else
            cont=exit
        fi
        cd $pathtomusic
        echo "[i] Path where i will download music : $pathtomusic"
        echo "[i] I will $cont if i found a file that already exist"
    else
        echo '[i] The config file do not exist...'
        echo '[i] Please run the Installer First or add The sample config file'
        exit
    fi

    [ "$continue" = "true" ] && cont=":"
}

function settags() {
    artist=$1
    title=$2
    filename=$3
    genre=$4
    imageurl=$5
    album=$6
    curl -s -L --user-agent 'Mozilla/5.0' "$imageurl" -o "/tmp/1.jpg"
    if [ "$writags" = "1" ] ; then
        eyeD3 --remove-all "$filename" &>/dev/null
        eyeD3 --add-image="/tmp/1.jpg:ILLUSTRATION" --add-image="/tmp/1.jpg:OTHER" --add-image="/tmp/1.jpg:MEDIA" --add-image="/tmp/1.jpg:ICON" --add-image="/tmp/1.jpg:MEDIA" --add-image="/tmp/1.jpg:OTHER_ICON" --add-image="/tmp/1.jpg:FRONT_COVER" -a "$artist" -Y $(date +%Y) -G "$genre" -t "$title" -A "$album" -2 "$filename" &>/dev/null
        echo '[i] Setting tags finished!'
    else
        echo "[i] Setting tags skipped (please install eyeD3)"
    fi
}

function downsong() {
    url="$1"
    echo "[i] Grabbing artists page"
    page=$(CURL $url)
    clientID=$(echo "$page" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    songid=$(echo "$page" | grep -v "small" | grep -oE "data-sc-track=.[0-9]*" | grep -oE "[0-9].*" | sort | uniq)

    songinfo=$(CURL "http://api.soundcloud.com/tracks/$songid.json?client_id=$clientID" | tr "," "\n")
    title=$(echo -e "$songinfo" | grep "title" | cut -d '"' -f 4 |  tr -d "\n" )
    filename=$(echo -e "$title".mp3 | tr '*/\?"<>|' '+       ' )
    songurl=$(echo -e "$songinfo" | grep "stream_url" | cut -d '"' -f 4)
    realsongurl=$(echo -e "$songurl?client_id=$clientID")
    artist=$(echo -e "$songinfo" | grep "username" | cut -d '"' -f 4)
    imageurl=$(echo -e "$songinfo" | grep "artwork_url" | cut -d '"' -f 4 | sed 's/large/t500x500/g')
    genre=$(echo -e "$songinfo" | grep "genre" | cut -d '"' -f 4)

    if [ -e "$filename" ]; then
        echo "[!] The song $filename has already been downloaded..."  && $cont
    else
        echo "[-] Downloading $title..."
        curl -# -L --user-agent 'Mozilla/5.0' -o "`echo -e "$filename"`" "$realsongurl";
        settags "$artist" "$title" "$filename" "$genre" "$imageurl"
        echo -e "[i] Downloading of $filename finished\n"
    fi
}

function downlike() {
    artistnm=$(echo "$1" | cut -d '/' -f 4)
    likeurl=$(echo "http://soundcloud.com/$artistnm")
    echo "[i] Grabbing artist's likes page"
    page=$(CURL $likeurl)
    clientID=$(echo "$page" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    artistID=$(CURL "http://api.soundcloud.com/resolve.json?url=$likeurl&client_id=$clientID" | grep -Po '(?<=/)[0-9]*(?=\.json)')

    offset=0
    stilllikessongs=1
    while [[ $stilllikessongs == "1" ]]
    do
        likepage=$(CURL "http://api.soundcloud.com/users/$artistID/favorites.json?client_id=$clientID&limit=1&offset=$offset")
        if [[ "$likepage" == "[]" ]]; then
            stilllikessongs=0
            echo "[i] There was $offset songs."
        else
            ((offset++))
            likesongurl=$(echo "$likepage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | cut -d '"' -f 4)
            echo ""
            echo "[i] Song liked n°$offset"
            downsong "$likesongurl"
        fi
    done

}

function downallsongs() {
    url="$1"
    echo "[i] Grabbing artists page"
    page=$(CURL $url)
    clientID=$(echo "$page" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    artistID=$(CURL "http://api.soundcloud.com/resolve.json?url=$url&client_id=$clientID" | grep -Po '(?<=/)[0-9]*(?=\.json)')
    
    offset=0
    stillsongs=1
    while [[ $stillsongs == "1" ]]
    do
        artistpage=$(CURL "https://api.sndcdn.com/e1/users/$artistID/sounds.json?limit=1&offset=$offset&client_id=$clientID")
        if [[ "$artistpage" == "[]" ]]; then
            stillsongs=0
            echo "[i] There was $offset songs."
        else
            ((offset++))
            typesong=$(echo "$artistpage" | tr "," "\n" | grep 'type' | cut -d '"' -f 4)
            if [[ "$typesong" == "track" ]]; then
                artistsongurl=$(echo "$artistpage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | cut -d '"' -f 4)
                echo ""
                echo "[i] Song n°$offset"
                downsong "$artistsongurl"
            elif [[ "$typesong" == "playlist" ]]; then
                artistsongurl=$(echo "$artistpage" | tr "," "\n" | grep 'permalink_url' | cut -d '"' -f 4)
                echo ""
                echo "[i] Song n°$offset"
                downset "$artistsongurl"
            elif [[ "$typesong" == "playlist_repost" ]]; then
                artistsongurl=$(echo "$artistpage" | tr "," "\n" | grep 'permalink_url' | cut -d '"' -f 4)
                echo ""
                echo "[i] Song n°$offset"
                downset "$artistsongurl"
            elif [[ "$typesong" == "track_repost" ]]; then
                artistsongurl=$(echo "$artistpage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | cut -d '"' -f 4)
                echo ""
                echo "[i] Song n°$offset"
                downsong "$artistsongurl"
            fi

        fi
    done
}

function downset() {
    echo "[i] Grabbing set page"
    url="$1"
    setpage=$(CURL $url)
    clientID=$(echo "$setpage" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    playlistid=$(echo -e "$setpage" | grep 'data-sc-playlist-id' | sed -n '1p'| cut -d '"' -f 4)

    offset=0
    stilllikessongs=1
    while [[ $stilllikessongs == "1" ]]
    do
        setpage=$(CURL "https://api.soundcloud.com/playlists/$playlistid.json?limit=1&offset=$offset&client_id=$clientID")
        if [[ "$setpage" == "[]" ]]; then
            stilllikessongs=0
            echo "[i] There was $offset songs."
        else
            ((offset++))
            setsongurl=$(echo "$setpage" | tr "," "\n" | grep 'permalink_url' | sed -n '4p' | cut -d '"' -f 4)
            echo ""
            echo "[i] Song liked n°$offset"
            downsong "$setsongurl"
        fi
    done
}

function downallsets() {
    artistnm=$(echo "$1" | cut -d '/' -f 4)
    seturl=$(echo "http://soundcloud.com/$artistnm")
    echo "[i] Grabbing artist's set page"
    page=$(CURL $seturl)
    clientID=$(echo "$page" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    artistID=$(CURL "http://api.soundcloud.com/resolve.json?url=$seturl&client_id=$clientID" | grep -Po '(?<=/)[0-9]*(?=\.json)')
    
    offset=0
    stilllikessongs=1
    while [[ $stilllikessongs == "1" ]]
    do
        allsetpage=$(CURL "https://api.soundcloud.com/users/$artistID/playlists.json?limit=1&offset=$offset&client_id=$clientID")
        if [[ "$allsetpage" == "[]" ]]; then
            stilllikessongs=0
            echo "[i] There was $offset songs."
        else
            ((offset++))
            thisset=$(echo "$allsetpage" | tr "," "\n" | grep 'permalink_url' | sed -n '1p'| cut -d '"' -f 4)
            echo ""
            echo "[i] Set n°$offset"
            downset "$thisset"
            echo "[i] Set n°$offset downloaded"
        fi
    done

}

function downgroup() {
    groupurl="$1"
    echo "[i] Grabbing group page"
    groupage=$(CURL "$groupurl")
    groupid=$(echo "$groupage" | grep "html5-code-groups" | tr " " "\n" | grep "html5-code-groups-" | cut -d '"' -f 2 | sed '2d' | cut -d '-' -f 4)
    clientID=$(echo "$groupage" | grep "clientID" | tr "," "\n" | grep "clientID" | cut -d '"' -f 4)
    trackspage=$(CURL "http://api.soundcloud.com/groups/$groupid/tracks.json?client_id=$clientID" | tr "}" "\n")
    trackspage=$(echo "$trackspage" | tr "," "\n" | grep 'permalink_url' | sed '1d' | sed -n '1~2p')
    songcount=$(echo "$trackspage" | wc -l)
    echo "[i] Found $songcount songs!"
    for (( i=1; i <= $songcount; i++ ))
    do
        echo -e "\n---------- Downloading Song n°$i ----------"
        thisongurl=$(echo "$trackspage" | sed -n "$i"p | cut -d '"' -f 4)
        downsong "$thisongurl"
        echo "----- Downloading Song n°$i finished ------"
    done
}

function show_help() {
    echo ""
    echo "[i] Usage: `basename $0` [url]"
    echo "    With url like :"
    echo "        http://soundcloud.com/user (Download all of one user's songs)"
    echo "        http://soundcloud.com/user/song-name (Download one single song)"
    echo "        http://soundcloud.com/user/sets (Download all of one user's sets)"
    echo "        http://soundcloud.com/user/sets/set-name (Download one single set)"
    echo ""
    echo "   Downloaded file names like : "title.mp3""
    echo ""
}

if [ -z "$1" ] || [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
    show_help
    exit 1
fi

clientID="b45b1aa10f1ac2941910a7f0d10f8e28"
writags=1

curlinstalled=`command -V curl &>/dev/null`

if $curlinstalled; then
    echo "[i] Using" `curl -V` | cut -c-21
else
    echo "[!] cURL need to be installed."; exit 1;
fi

command -v eyeD3 &>/dev/null || { echo "[!] eyeD3 needs to be installed to write tags into mp3 file."; echo "[!] The script will skip this part..."; writags=0; }

soundurl=$(echo "$1" | sed 's-.*soundcloud.com/-http://soundcloud.com/-' | cut -d "?" -f 1 | grep 'soundcloud.com')

echo "[i] Using URL $soundurl"
config

d1="$(echo "$soundurl" | cut -d "/" -f 4)"
d2="$(echo "$soundurl" | cut -d "/" -f 5)"
d3="$(echo "$soundurl" | cut -d "/" -f 6)"

if [[ "$d1" == "" ]] ; then
    echo "[!] Bad URL!"
    show_help
    exit 1
elif [[ "$d1" == "groups" ]] ; then
    echo "[i] Detected download type : All song of the group"
    downgroup "$soundurl"
elif [[ "$d2" == "likes" ]] ; then
    echo "[i] Detected download type : All of one user's like"
    downlike "$soundurl"
elif [[ "$d2" == "" ]] ; then
    echo "[i] Detected download type : All of one user's songs"
    downallsongs "$soundurl"
elif [[ "$d2" == "sets" ]] && [[ "$d3" == "" ]] ; then
    echo "[i] Detected download type : All of one user's sets"
    downallsets "$soundurl"
elif [[ "$d2" == "sets" ]] ; then
    echo "[i] Detected download type : One single set"
    downset "$soundurl"
else
    echo "[i] Detected download type : One single song"
    downsong "$soundurl"
fi
